version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: SuperVeiligWachtwoord123@!
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  api:
    build:
        context: ./backend/backend/
        dockerfile: ./Dockerfile
    ports:
      - "5080:8080"
      - "5081:8081"
    restart: always
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: ./backend/

  client:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    ports:
      - "4080:4080"
    restart: always
    depends_on:
      - api
    develop:
      watch:
        - action: rebuild
          path: ./frontend/

volumes:
  pgdata: