version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: SuperVeiligWachtwoord123@!
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  api:
    # student uitwerking
    ports:
      - "5080:8080"
      - "5081:8081"
    # student uitwerking
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: ./backend/

  client:
    # student uitwerking

volumes:
  pgdata: